CREATE TABLE users
(
    Id SERIAL PRIMARY KEY,
    Login CHARACTER VARYING UNIQUE NOT NULL
);

CREATE TABLE files
(
    Id SERIAL PRIMARY KEY,
    Hash CHARACTER VARYING(44) UNIQUE NOT NULL,
    Bin bytea
);

CREATE TABLE userfiles
(
    Id SERIAL PRIMARY KEY,
    UserId INTEGER REFERENCES users (Id) NOT NULL,
    FileName CHARACTER VARYING NOT NULL,
	ContentType CHARACTER VARYING NOT NULL,
    Hash CHARACTER VARYING(44) REFERENCES files (Hash) NOT NULL
);